const LOCALE_FLAGS: Record<string, { flag: string; name: string }> = {
  en: { flag: "\u{1F1FA}\u{1F1F8}", name: "English" },
  es: { flag: "\u{1F1EA}\u{1F1F8}", name: "Spanish" },
  fr: { flag: "\u{1F1EB}\u{1F1F7}", name: "French" },
  de: { flag: "\u{1F1E9}\u{1F1EA}", name: "German" },
  it: { flag: "\u{1F1EE}\u{1F1F9}", name: "Italian" },
  pt: { flag: "\u{1F1E7}\u{1F1F7}", name: "Portuguese" },
  "pt-BR": { flag: "\u{1F1E7}\u{1F1F7}", name: "Portuguese (Brazil)" },
  ja: { flag: "\u{1F1EF}\u{1F1F5}", name: "Japanese" },
  ko: { flag: "\u{1F1F0}\u{1F1F7}", name: "Korean" },
  zh: { flag: "\u{1F1E8}\u{1F1F3}", name: "Chinese" },
  "zh-TW": { flag: "\u{1F1F9}\u{1F1FC}", name: "Chinese (Traditional)" },
  ar: { flag: "\u{1F1F8}\u{1F1E6}", name: "Arabic" },
  hi: { flag: "\u{1F1EE}\u{1F1F3}", name: "Hindi" },
  ru: { flag: "\u{1F1F7}\u{1F1FA}", name: "Russian" },
  nl: { flag: "\u{1F1F3}\u{1F1F1}", name: "Dutch" },
  sv: { flag: "\u{1F1F8}\u{1F1EA}", name: "Swedish" },
  da: { flag: "\u{1F1E9}\u{1F1F0}", name: "Danish" },
  fi: { flag: "\u{1F1EB}\u{1F1EE}", name: "Finnish" },
  no: { flag: "\u{1F1F3}\u{1F1F4}", name: "Norwegian" },
  pl: { flag: "\u{1F1F5}\u{1F1F1}", name: "Polish" },
  tr: { flag: "\u{1F1F9}\u{1F1F7}", name: "Turkish" },
  th: { flag: "\u{1F1F9}\u{1F1ED}", name: "Thai" },
  vi: { flag: "\u{1F1FB}\u{1F1F3}", name: "Vietnamese" },
  id: { flag: "\u{1F1EE}\u{1F1E9}", name: "Indonesian" },
  uk: { flag: "\u{1F1FA}\u{1F1E6}", name: "Ukrainian" },
  cs: { flag: "\u{1F1E8}\u{1F1FF}", name: "Czech" },
  ro: { flag: "\u{1F1F7}\u{1F1F4}", name: "Romanian" },
  hu: { flag: "\u{1F1ED}\u{1F1FA}", name: "Hungarian" },
  el: { flag: "\u{1F1EC}\u{1F1F7}", name: "Greek" },
  he: { flag: "\u{1F1EE}\u{1F1F1}", name: "Hebrew" },
  bn: { flag: "\u{1F1E7}\u{1F1E9}", name: "Bengali" },
  ms: { flag: "\u{1F1F2}\u{1F1FE}", name: "Malay" },
  "en-GB": { flag: "\u{1F1EC}\u{1F1E7}", name: "English (UK)" },
  "en-US": { flag: "\u{1F1FA}\u{1F1F8}", name: "English (US)" },
  "es-MX": { flag: "\u{1F1F2}\u{1F1FD}", name: "Spanish (Mexico)" },
  "fr-CA": { flag: "\u{1F1E8}\u{1F1E6}", name: "French (Canada)" },
};

export function getLocaleInfo(locale: string): { flag: string; name: string } {
  return LOCALE_FLAGS[locale] ?? { flag: "\u{1F310}", name: locale };
}
